prefix = "2a02:8071:6720:2c86::/59"

[mapping]
"fd05::/64" = "2a02:8071:6720:2c9f::/64"
"fd04::/64" = "2a02:8071:6720:2c9e::/64"
"fd03::/64" = "2a02:8071:6720:2c9d::/64"
"fd02::/64" = "2a02:8071:6720:2c9c::/64"
