prefix = "2a02:8071:6720:2a80::/59"

[mapping]
"fd05::/64" = "2a02:8071:6720:2a9f::/64"
"fd04::/64" = "2a02:8071:6720:2a9e::/64"
"fd03::/64" = "2a02:8071:6720:2a9d::/64"
"fd02::/64" = "2a02:8071:6720:2a9c::/64"